### ISSUE TITLE
conan_cmake_run cannot run success in CMakeLists

### ISSUE THREAD

**Issue by xRobinJiang** [open62541/nodesetLoader#162]

**Comment by xRobinJiang** [comment]
When I cmake ..  the project ,  i find that download conan and run conan_cmake_run always has some error.

**Comment by matkonnerth** [comment]
I removed the open62541 library as conan dependency, because nodesetLoader needs version >= 1.2 of open26541, and this version is currently not available via conan: https://github.com/matkonnerth/nodesetLoader/pull/164

**Comment by matkonnerth** [comment]
@xRobinJiang : any progress on this issue?
