### ISSUE TITLE
Valgrind Memory leak in xmlCreatePushParserCtxt() Output

### ISSUE THREAD

**Issue by Fischer-Thomas** [open62541/nodesetLoader#190]
Valgrind reports a memory leak for me in this repository.

> ==3600== 400 bytes in 1 blocks are still reachable in loss record 19 of 19
==3600==    at 0x4842839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3600==    by 0x48D5D71: xmlInitCharEncodingHandlers (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10)
==3600==    by 0x48D667C: xmlGetCharEncodingHandler (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10)
==3600==    by 0x49165E5: xmlAllocParserInputBuffer (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10)
==3600==    by 0x48F1992: xmlCreatePushParserCtxt (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10)
==3600==    by 0x3F7744: Parser_run (Parser.c:50)
==3600==    by 0x3F42C0: NodesetLoader_importFile (NodesetLoader.c:499)
==3600==    by 0x3EF1AB: NodesetLoader_loadFile (import.c:601)

As you can see from the logs the problem is in https://github.com/matkonnerth/nodesetLoader/blob/150da27b24ff2f5da237c2919acd1ec5bc316856/src/Parser.c#L50

I found the following issue in the GNOME gitlab regarding libxml2: 
https://gitlab.gnome.org/GNOME/libxml2/-/issues/9

The Issues hints, that the xmlInitParser() function call is missing before the xmlCeatePushParserCtxt() function is called. 
After adding this line valgrind no longer reports the memory leak.

**Comment by matkonnerth** [comment]
Thank you for reporting this issue, have to check why the automated tests with valgrind are not reporting this leak. Can you propose a PR with the fix?
